version: "3.4"
services:
  alinakz-test1:
    image: node:alpine
    container_name: alinakz-test1-docker
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
